/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import javax.swing.JDesktopPane;
import Classes.Airline;
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import net.proteanit.sql.DbUtils;
import javax.swing.table.*;
/**
 *
 * @author Chaithika
 */
public class Manageairline extends javax.swing.JInternalFrame {

    /**
     * Creates new form Manageairline
     */
    public Manageairline() {
        initComponents();
        tableload();
        v1.setVisible(false);
        v2.setVisible(false);
        v3.setVisible(false);
        
    }
    
    private void resetFields(){
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jCheckBox1.setSelected(false);
            }
    private void tableload()
    {
        Airline airLine = new Airline();
        ResultSet rs = airLine.getAll();
        if(rs == null)
        {
            return;
        }
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        
        jTable1.setBackground(Color.yellow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        v1 = new javax.swing.JLabel();
        v2 = new javax.swing.JLabel();
        v3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(920, 735));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Airline ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(25, 108, 56, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Airline Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(25, 150, 75, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Origin");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(25, 191, 36, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Active");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(25, 229, 38, 15);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(117, 103, 150, 22);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(117, 148, 150, 22);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(117, 189, 150, 22);

        v1.setForeground(new java.awt.Color(255, 0, 0));
        v1.setText("*");
        getContentPane().add(v1);
        v1.setBounds(87, 109, 8, 16);

        v2.setForeground(new java.awt.Color(255, 0, 0));
        v2.setText("*");
        getContentPane().add(v2);
        v2.setBounds(106, 151, 8, 16);

        v3.setForeground(new java.awt.Color(255, 0, 0));
        v3.setText("*");
        getContentPane().add(v3);
        v3.setBounds(67, 192, 8, 16);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Airline_ID", "Airline Name", "Origin", "Active"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(305, 103, 570, 100);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jButton1.setText("Reset");
        getContentPane().add(jButton1);
        jButton1.setBounds(196, 262, 71, 25);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(755, 12, 120, 37);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Edit Airline Details");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(610, 340, 143, 42);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Add Airline");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(430, 340, 144, 42);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Manage Airline");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(434, 11, 189, 37);
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(117, 229, 25, 25);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setText("Add Airline");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(430, 340, 144, 42);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("Add Airline");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(430, 340, 144, 42);

        jButton8.setText("Print");
        getContentPane().add(jButton8);
        jButton8.setBounds(280, 335, 120, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/air-new-airline.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 900, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JDesktopPane desktopPane = getDesktopPane();
        Adminlogin ma =new Adminlogin();
        desktopPane.add(ma);
        ma.setVisible(true);
        this.dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int d =JOptionPane.showConfirmDialog(null, "Press yes to update");
        
        if( d == 0){
            
            int row = jTable1.getSelectedRow();
            if (row == -1){
                JOptionPane.showMessageDialog(rootPane, "Error: no row selected");
                return;
            }
            Airline a1 = new Airline((String) jTable1.getValueAt(row, 0));
            if(!a1.getAirline_ID().equals(jTextField1.getText())) {
                JOptionPane.showMessageDialog(rootPane, "Cannot update non exhisting airport");
                return;
            }
            String airid = jTextField1.getText();
            String airname = jTextField2.getText();
            String org = jTextField3.getText();
            boolean airlineactive =jCheckBox1.isSelected();
            boolean validity = true;
            
            if (airid.isEmpty()|| jTextField1 ==null ){
                validity =false;
                v1.setVisible(true);   
            }
            if (airname.isEmpty()||jTextField2 == null){
                validity=false;
                v2.setVisible(true);
            }
            if (org.isEmpty()||jTextField3 == null){
                validity=false;
                v3.setVisible(true);
        }
            if (validity == true){
                a1.setAirline_ID(airid);
                a1.setAirline_name(airname);
                a1.setOrigin(org);
                a1.setActive(airlineactive);
                if(!a1.save()){
                    JOptionPane.showMessageDialog(rootPane, "Error: Data not saved");
                }else {
                    JOptionPane.showConfirmDialog(rootPane, "Saved Successfully");
                    this.resetFields();
                    v1.setVisible(false);
                    v2.setVisible(false);
                    v3.setVisible(false);
                }
               }
            this.tableload();
                
            }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
             String airid = jTextField1.getText();
             String airname = jTextField2.getText();
             String org = jTextField3.getText();
             boolean airlineactive = jCheckBox1.isSelected();
             boolean validity =true;
             
             if(airid.isEmpty()||jTextField1 == null) {
                 validity = false; 
                 v1.setVisible(true);
             }
              if(airname.isEmpty()||jTextField2 == null) {
                 validity = false; 
                 v2.setVisible(true);
              }
              if(org.isEmpty()||jTextField3 == null) {
                 validity = false; 
                 v3.setVisible(true);
              }
              if(validity == true){
                  Airline f1 = new Airline();
                  f1.setAirline_ID(airid);
                  f1.setAirline_name(airname);
                  f1.setOrigin(org);
                  f1.setActive(airlineactive);
                  if(!f1.save()){
                      JOptionPane.showMessageDialog(rootPane, "Error data not saved");
                  }else {
                      JOptionPane.showMessageDialog(rootPane, "Saved Successfully");
                      this.resetFields();
                      v1.setVisible(false);
                      v2.setVisible(false);
                      v3.setVisible(false);
                  }
              }
              this.tableload();
              
             
             
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row =jTable1.getSelectedRow();
        if(row == -1){
            return;
        }
        Airline f1 = new Airline(jTable1.getValueAt(row, 0).toString());
        jTextField1.setText(f1.getAirline_ID());
        jTextField2.setText(f1.getAirline_name());
        jTextField3.setText(f1.getOrigin());
        jCheckBox1.setSelected(f1.isActive());
// TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel v1;
    private javax.swing.JLabel v2;
    private javax.swing.JLabel v3;
    // End of variables declaration//GEN-END:variables
}
