/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Classes.FlightLeg;
import Classes.LegClasses;
import Classes.LegClasses;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author FRANKENSTEIN
 */
public class Managelegclasses extends javax.swing.JInternalFrame {

    /**
     * Creates new form Managelegclasses
     */
    public Managelegclasses() {
        initComponents();
        tableload();
        legnoLoad();
    }
    
        /**
     * Genarate data for jtable
     */
    private void tableload() {
        LegClasses lc = new LegClasses();
        ResultSet rs = lc.getAll();
        if (rs == null) {
            return;
        }
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));

    }
    
    private void resetFeilds() {
        jTextField1.setText("");
        jTextField2.setText("");				
        jComboBox1.setSelectedItem(null);				
    }
    
    private void legnoLoad() {		
        FlightLeg lc1 = new FlightLeg();		
        ResultSet rs = lc1.getAll();		
        jComboBox1.removeAllItems();		
        try {		
            while (rs.next()) {		
                String name = rs.getString("leg_no");		
                jComboBox1.addItem(name);			
            }		
        } catch (SQLException ex) {		
            Logger.getLogger(Manageflights.class.getName()).log(Level.SEVERE, null, ex);		
        }		
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setBorder(null);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Flight Leg", "Class", "Price"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(380, 80, 510, 100);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(120, 90, 119, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Flight Leg");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 99, 60, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Price");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 190, 40, 15);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(120, 190, 125, 22);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(120, 140, 125, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Class");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 140, 40, 15);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButton1.setText("Reset");
        getContentPane().add(jButton1);
        jButton1.setBounds(124, 243, 65, 23);

        jButton2.setText("Add Class");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(380, 210, 110, 35);

        jButton3.setText("Edit Class");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(510, 210, 110, 35);

        jButton4.setText("Delete Class");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(650, 210, 110, 35);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Manage Leg Classes");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(362, 20, 180, 22);

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(810, 35, 80, 30);

        setBounds(-5, -35, 910, 735);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         int d = JOptionPane.showConfirmDialog(null, "Press Yes to update");

        if (d == 0) {

            int row = jTable1.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(rootPane, "Error: no row selected");
                return;
            }
            LegClasses l1 = new LegClasses(Integer.parseInt(jTable1.getValueAt(row, 0).toString()),Integer.parseInt(jTable1.getValueAt(row, 1).toString()));
            Integer legno = Integer.parseInt(jComboBox1.getSelectedItem().toString());
            Integer class_ = Integer.parseInt(jTextField2.getText());
            Float price = Float.parseFloat(jTextField1.getText());
            boolean validity = true;
            
            if(legno==null)
            {
                validity = false;
            }
            if(class_ == null|| class_>3 || class_<1){
                validity = false;
            }
            if(price == null|| price<0){
                validity = false;
            }
            
            if(validity==true){
                LegClasses l2 = new LegClasses();
                l2.setLeg_no(legno);
                l2.setClass_(class_);
                l2.setPrice(price);
                if (l2.save()) {
                    JOptionPane.showMessageDialog(rootPane, "Data saved successfully");
                    tableload();
                } else {
                    return;
                }
            }
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JDesktopPane desktopPane = getDesktopPane();
        Adminlogin al = new Adminlogin();
        desktopPane.add(al);
        al.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            return;
        }
        LegClasses l1 = new LegClasses(Integer.parseInt(jTable1.getValueAt(row, 0).toString()),Integer.parseInt(jTable1.getValueAt(row, 1).toString()));
        jTextField1.setText(Float.toString(l1.getPrice()));
        jTextField2.setText(Integer.toString(l1.getClass_()));
        jComboBox1.setSelectedItem(l1.getLeg_no());
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            Integer legno = Integer.parseInt(jComboBox1.getSelectedItem().toString());
            Integer class_ = Integer.parseInt(jTextField2.getText());
            Float price = Float.parseFloat(jTextField1.getText());
            boolean validity = true;
            
            if(legno==null)
            {
                validity = false;
            }
            if(class_ == null|| class_>3 || class_<1){
                validity = false;
            }
            if(price == null|| price<0){
                validity = false;
            }
            
            if(validity==true){
                LegClasses l2 = new LegClasses();
                l2.setLeg_no(legno);
                l2.setClass_(class_);
                l2.setPrice(price);
                if (l2.save()) {
                    JOptionPane.showMessageDialog(rootPane, "Data saved successfully");
                    tableload();
                } else {
                    return;
                }
            }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
